INSERT INTO STAT_CAD VALUES ('A', 'Ativo');
INSERT INTO STAT_CAD VALUES ('I', 'Inativo');

INSERT INTO STAT_TOTEM VALUES ('I', 'Indisponível');
INSERT INTO STAT_TOTEM VALUES ('D', 'Disponível');
INSERT INTO STAT_TOTEM VALUES ('C', 'Carregando');
INSERT INTO STAT_TOTEM VALUES ('B', 'Bloqueado');

INSERT INTO STAT_USU VALUES ('A', 'Ativo');
INSERT INTO STAT_USU VALUES ('I', 'Inativo');
INSERT INTO STAT_USU VALUES ('B', 'Bloqueado');